// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"github.com/gofiber/fiber/v3"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRouter creates a new instance of MockRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRouter {
	mock := &MockRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRouter is an autogenerated mock type for the Router type
type MockRouter struct {
	mock.Mock
}

type MockRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRouter) EXPECT() *MockRouter_Expecter {
	return &MockRouter_Expecter{mock: &_m.Mock}
}

// Setup provides a mock function for the type MockRouter
func (_mock *MockRouter) Setup() {
	_mock.Called()
	return
}

// MockRouter_Setup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Setup'
type MockRouter_Setup_Call struct {
	*mock.Call
}

// Setup is a helper method to define mock.On call
func (_e *MockRouter_Expecter) Setup() *MockRouter_Setup_Call {
	return &MockRouter_Setup_Call{Call: _e.mock.On("Setup")}
}

func (_c *MockRouter_Setup_Call) Run(run func()) *MockRouter_Setup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRouter_Setup_Call) Return() *MockRouter_Setup_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouter_Setup_Call) RunAndReturn(run func()) *MockRouter_Setup_Call {
	_c.Run(run)
	return _c
}

// setupAuthRoutes provides a mock function for the type MockRouter
func (_mock *MockRouter) setupAuthRoutes(api fiber.Router) {
	_mock.Called(api)
	return
}

// MockRouter_setupAuthRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setupAuthRoutes'
type MockRouter_setupAuthRoutes_Call struct {
	*mock.Call
}

// setupAuthRoutes is a helper method to define mock.On call
//   - api fiber.Router
func (_e *MockRouter_Expecter) setupAuthRoutes(api any) *MockRouter_setupAuthRoutes_Call {
	return &MockRouter_setupAuthRoutes_Call{Call: _e.mock.On("setupAuthRoutes", api)}
}

func (_c *MockRouter_setupAuthRoutes_Call) Run(run func(api fiber.Router)) *MockRouter_setupAuthRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fiber.Router
		if args[0] != nil {
			arg0 = args[0].(fiber.Router)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRouter_setupAuthRoutes_Call) Return() *MockRouter_setupAuthRoutes_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouter_setupAuthRoutes_Call) RunAndReturn(run func(api fiber.Router)) *MockRouter_setupAuthRoutes_Call {
	_c.Run(run)
	return _c
}

// setupPixelRoutes provides a mock function for the type MockRouter
func (_mock *MockRouter) setupPixelRoutes(api fiber.Router) {
	_mock.Called(api)
	return
}

// MockRouter_setupPixelRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setupPixelRoutes'
type MockRouter_setupPixelRoutes_Call struct {
	*mock.Call
}

// setupPixelRoutes is a helper method to define mock.On call
//   - api fiber.Router
func (_e *MockRouter_Expecter) setupPixelRoutes(api any) *MockRouter_setupPixelRoutes_Call {
	return &MockRouter_setupPixelRoutes_Call{Call: _e.mock.On("setupPixelRoutes", api)}
}

func (_c *MockRouter_setupPixelRoutes_Call) Run(run func(api fiber.Router)) *MockRouter_setupPixelRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fiber.Router
		if args[0] != nil {
			arg0 = args[0].(fiber.Router)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRouter_setupPixelRoutes_Call) Return() *MockRouter_setupPixelRoutes_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouter_setupPixelRoutes_Call) RunAndReturn(run func(api fiber.Router)) *MockRouter_setupPixelRoutes_Call {
	_c.Run(run)
	return _c
}

// setupSettingRoutes provides a mock function for the type MockRouter
func (_mock *MockRouter) setupSettingRoutes(api fiber.Router) {
	_mock.Called(api)
	return
}

// MockRouter_setupSettingRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setupSettingRoutes'
type MockRouter_setupSettingRoutes_Call struct {
	*mock.Call
}

// setupSettingRoutes is a helper method to define mock.On call
//   - api fiber.Router
func (_e *MockRouter_Expecter) setupSettingRoutes(api any) *MockRouter_setupSettingRoutes_Call {
	return &MockRouter_setupSettingRoutes_Call{Call: _e.mock.On("setupSettingRoutes", api)}
}

func (_c *MockRouter_setupSettingRoutes_Call) Run(run func(api fiber.Router)) *MockRouter_setupSettingRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fiber.Router
		if args[0] != nil {
			arg0 = args[0].(fiber.Router)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRouter_setupSettingRoutes_Call) Return() *MockRouter_setupSettingRoutes_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouter_setupSettingRoutes_Call) RunAndReturn(run func(api fiber.Router)) *MockRouter_setupSettingRoutes_Call {
	_c.Run(run)
	return _c
}

// setupUserRoutes provides a mock function for the type MockRouter
func (_mock *MockRouter) setupUserRoutes(api fiber.Router) {
	_mock.Called(api)
	return
}

// MockRouter_setupUserRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setupUserRoutes'
type MockRouter_setupUserRoutes_Call struct {
	*mock.Call
}

// setupUserRoutes is a helper method to define mock.On call
//   - api fiber.Router
func (_e *MockRouter_Expecter) setupUserRoutes(api any) *MockRouter_setupUserRoutes_Call {
	return &MockRouter_setupUserRoutes_Call{Call: _e.mock.On("setupUserRoutes", api)}
}

func (_c *MockRouter_setupUserRoutes_Call) Run(run func(api fiber.Router)) *MockRouter_setupUserRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fiber.Router
		if args[0] != nil {
			arg0 = args[0].(fiber.Router)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRouter_setupUserRoutes_Call) Return() *MockRouter_setupUserRoutes_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouter_setupUserRoutes_Call) RunAndReturn(run func(api fiber.Router)) *MockRouter_setupUserRoutes_Call {
	_c.Run(run)
	return _c
}

// setupWebsocketRoutes provides a mock function for the type MockRouter
func (_mock *MockRouter) setupWebsocketRoutes(api fiber.Router) {
	_mock.Called(api)
	return
}

// MockRouter_setupWebsocketRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setupWebsocketRoutes'
type MockRouter_setupWebsocketRoutes_Call struct {
	*mock.Call
}

// setupWebsocketRoutes is a helper method to define mock.On call
//   - api fiber.Router
func (_e *MockRouter_Expecter) setupWebsocketRoutes(api any) *MockRouter_setupWebsocketRoutes_Call {
	return &MockRouter_setupWebsocketRoutes_Call{Call: _e.mock.On("setupWebsocketRoutes", api)}
}

func (_c *MockRouter_setupWebsocketRoutes_Call) Run(run func(api fiber.Router)) *MockRouter_setupWebsocketRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fiber.Router
		if args[0] != nil {
			arg0 = args[0].(fiber.Router)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRouter_setupWebsocketRoutes_Call) Return() *MockRouter_setupWebsocketRoutes_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRouter_setupWebsocketRoutes_Call) RunAndReturn(run func(api fiber.Router)) *MockRouter_setupWebsocketRoutes_Call {
	_c.Run(run)
	return _c
}
