// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"go-place/internal/model/request"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockService
func (_mock *MockService) Login(credentials *request.AuthCredentials) (*string, error) {
	ret := _mock.Called(credentials)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*request.AuthCredentials) (*string, error)); ok {
		return returnFunc(credentials)
	}
	if returnFunc, ok := ret.Get(0).(func(*request.AuthCredentials) *string); ok {
		r0 = returnFunc(credentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*request.AuthCredentials) error); ok {
		r1 = returnFunc(credentials)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - credentials *request.AuthCredentials
func (_e *MockService_Expecter) Login(credentials any) *MockService_Login_Call {
	return &MockService_Login_Call{Call: _e.mock.On("Login", credentials)}
}

func (_c *MockService_Login_Call) Run(run func(credentials *request.AuthCredentials)) *MockService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *request.AuthCredentials
		if args[0] != nil {
			arg0 = args[0].(*request.AuthCredentials)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Login_Call) Return(s *string, err error) *MockService_Login_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_Login_Call) RunAndReturn(run func(credentials *request.AuthCredentials) (*string, error)) *MockService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockService
func (_mock *MockService) Register(credentials *request.AuthCredentials) (*string, error) {
	ret := _mock.Called(credentials)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*request.AuthCredentials) (*string, error)); ok {
		return returnFunc(credentials)
	}
	if returnFunc, ok := ret.Get(0).(func(*request.AuthCredentials) *string); ok {
		r0 = returnFunc(credentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*request.AuthCredentials) error); ok {
		r1 = returnFunc(credentials)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - credentials *request.AuthCredentials
func (_e *MockService_Expecter) Register(credentials any) *MockService_Register_Call {
	return &MockService_Register_Call{Call: _e.mock.On("Register", credentials)}
}

func (_c *MockService_Register_Call) Run(run func(credentials *request.AuthCredentials)) *MockService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *request.AuthCredentials
		if args[0] != nil {
			arg0 = args[0].(*request.AuthCredentials)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Register_Call) Return(s *string, err error) *MockService_Register_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_Register_Call) RunAndReturn(run func(credentials *request.AuthCredentials) (*string, error)) *MockService_Register_Call {
	_c.Call.Return(run)
	return _c
}
