// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"github.com/gofiber/fiber/v3"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockHandler
func (_mock *MockHandler) Login(ctx fiber.Ctx) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(fiber.Ctx) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockHandler_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx fiber.Ctx
func (_e *MockHandler_Expecter) Login(ctx any) *MockHandler_Login_Call {
	return &MockHandler_Login_Call{Call: _e.mock.On("Login", ctx)}
}

func (_c *MockHandler_Login_Call) Run(run func(ctx fiber.Ctx)) *MockHandler_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(fiber.Ctx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_Login_Call) Return(err error) *MockHandler_Login_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_Login_Call) RunAndReturn(run func(ctx fiber.Ctx) error) *MockHandler_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockHandler
func (_mock *MockHandler) Register(ctx fiber.Ctx) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(fiber.Ctx) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockHandler_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx fiber.Ctx
func (_e *MockHandler_Expecter) Register(ctx any) *MockHandler_Register_Call {
	return &MockHandler_Register_Call{Call: _e.mock.On("Register", ctx)}
}

func (_c *MockHandler_Register_Call) Run(run func(ctx fiber.Ctx)) *MockHandler_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(fiber.Ctx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_Register_Call) Return(err error) *MockHandler_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_Register_Call) RunAndReturn(run func(ctx fiber.Ctx) error) *MockHandler_Register_Call {
	_c.Call.Return(run)
	return _c
}
