// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package server

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockApp creates a new instance of MockApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApp {
	mock := &MockApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockApp is an autogenerated mock type for the App type
type MockApp struct {
	mock.Mock
}

type MockApp_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApp) EXPECT() *MockApp_Expecter {
	return &MockApp_Expecter{mock: &_m.Mock}
}

// Shutdown provides a mock function for the type MockApp
func (_mock *MockApp) Shutdown() {
	_mock.Called()
	return
}

// MockApp_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockApp_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *MockApp_Expecter) Shutdown() *MockApp_Shutdown_Call {
	return &MockApp_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *MockApp_Shutdown_Call) Run(run func()) *MockApp_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockApp_Shutdown_Call) Return() *MockApp_Shutdown_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockApp_Shutdown_Call) RunAndReturn(run func()) *MockApp_Shutdown_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type MockApp
func (_mock *MockApp) Start() {
	_mock.Called()
	return
}

// MockApp_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockApp_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockApp_Expecter) Start() *MockApp_Start_Call {
	return &MockApp_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockApp_Start_Call) Run(run func()) *MockApp_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockApp_Start_Call) Return() *MockApp_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockApp_Start_Call) RunAndReturn(run func()) *MockApp_Start_Call {
	_c.Run(run)
	return _c
}
