// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package setting

import (
	"go-place/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(setting *model.Setting) error {
	ret := _mock.Called(setting)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Setting) error); ok {
		r0 = returnFunc(setting)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - setting *model.Setting
func (_e *MockService_Expecter) Create(setting any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", setting)}
}

func (_c *MockService_Create_Call) Run(run func(setting *model.Setting)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Setting
		if args[0] != nil {
			arg0 = args[0].(*model.Setting)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(err error) *MockService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(setting *model.Setting) error) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockService
func (_mock *MockService) Get() (*model.Setting, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *model.Setting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*model.Setting, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *model.Setting); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Setting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockService_Expecter) Get() *MockService_Get_Call {
	return &MockService_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockService_Get_Call) Run(run func()) *MockService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Get_Call) Return(setting *model.Setting, err error) *MockService_Get_Call {
	_c.Call.Return(setting, err)
	return _c
}

func (_c *MockService_Get_Call) RunAndReturn(run func() (*model.Setting, error)) *MockService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(setting *model.Setting) error {
	ret := _mock.Called(setting)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Setting) error); ok {
		r0 = returnFunc(setting)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - setting *model.Setting
func (_e *MockService_Expecter) Update(setting any) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", setting)}
}

func (_c *MockService_Update_Call) Run(run func(setting *model.Setting)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Setting
		if args[0] != nil {
			arg0 = args[0].(*model.Setting)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(err error) *MockService_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(setting *model.Setting) error) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}
