// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package setting

import (
	"github.com/gofiber/fiber/v3"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockHandler
func (_mock *MockHandler) Get(ctx fiber.Ctx) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(fiber.Ctx) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockHandler_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx fiber.Ctx
func (_e *MockHandler_Expecter) Get(ctx any) *MockHandler_Get_Call {
	return &MockHandler_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *MockHandler_Get_Call) Run(run func(ctx fiber.Ctx)) *MockHandler_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(fiber.Ctx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_Get_Call) Return(err error) *MockHandler_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_Get_Call) RunAndReturn(run func(ctx fiber.Ctx) error) *MockHandler_Get_Call {
	_c.Call.Return(run)
	return _c
}
