// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"github.com/gofiber/fiber/v3"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockHandler
func (_mock *MockHandler) GetByID(ctx fiber.Ctx) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(fiber.Ctx) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockHandler_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx fiber.Ctx
func (_e *MockHandler_Expecter) GetByID(ctx any) *MockHandler_GetByID_Call {
	return &MockHandler_GetByID_Call{Call: _e.mock.On("GetByID", ctx)}
}

func (_c *MockHandler_GetByID_Call) Run(run func(ctx fiber.Ctx)) *MockHandler_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(fiber.Ctx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_GetByID_Call) Return(err error) *MockHandler_GetByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_GetByID_Call) RunAndReturn(run func(ctx fiber.Ctx) error) *MockHandler_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentUser provides a mock function for the type MockHandler
func (_mock *MockHandler) GetCurrentUser(ctx fiber.Ctx) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(fiber.Ctx) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_GetCurrentUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentUser'
type MockHandler_GetCurrentUser_Call struct {
	*mock.Call
}

// GetCurrentUser is a helper method to define mock.On call
//   - ctx fiber.Ctx
func (_e *MockHandler_Expecter) GetCurrentUser(ctx any) *MockHandler_GetCurrentUser_Call {
	return &MockHandler_GetCurrentUser_Call{Call: _e.mock.On("GetCurrentUser", ctx)}
}

func (_c *MockHandler_GetCurrentUser_Call) Run(run func(ctx fiber.Ctx)) *MockHandler_GetCurrentUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(fiber.Ctx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_GetCurrentUser_Call) Return(err error) *MockHandler_GetCurrentUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_GetCurrentUser_Call) RunAndReturn(run func(ctx fiber.Ctx) error) *MockHandler_GetCurrentUser_Call {
	_c.Call.Return(run)
	return _c
}
