// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"go-place/internal/database"
	"go-place/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(user *model.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user *model.User
func (_e *MockService_Expecter) Create(user any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", user)}
}

func (_c *MockService_Create_Call) Run(run func(user *model.User)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.User
		if args[0] != nil {
			arg0 = args[0].(*model.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(err error) *MockService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(user *model.User) error) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockService_Expecter) Delete(id any) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockService_Delete_Call) Run(run func(id uint64)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(id uint64) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockService
func (_mock *MockService) GetAll(opts ...database.Option) ([]model.User, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(opts)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...database.Option) ([]model.User, error)); ok {
		return returnFunc(opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(...database.Option) []model.User); ok {
		r0 = returnFunc(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...database.Option) error); ok {
		r1 = returnFunc(opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - opts ...database.Option
func (_e *MockService_Expecter) GetAll(opts ...any) *MockService_GetAll_Call {
	return &MockService_GetAll_Call{Call: _e.mock.On("GetAll",
		append([]any{}, opts...)...)}
}

func (_c *MockService_GetAll_Call) Run(run func(opts ...database.Option)) *MockService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []database.Option
		var variadicArgs []database.Option
		if len(args) > 0 {
			variadicArgs = args[0].([]database.Option)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockService_GetAll_Call) Return(users []model.User, err error) *MockService_GetAll_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockService_GetAll_Call) RunAndReturn(run func(opts ...database.Option) ([]model.User, error)) *MockService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockService
func (_mock *MockService) GetByID(id uint64, opts ...database.Option) (*model.User, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(id, opts)
	} else {
		tmpRet = _mock.Called(id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, ...database.Option) (*model.User, error)); ok {
		return returnFunc(id, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, ...database.Option) *model.User); ok {
		r0 = returnFunc(id, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, ...database.Option) error); ok {
		r1 = returnFunc(id, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint64
//   - opts ...database.Option
func (_e *MockService_Expecter) GetByID(id any, opts ...any) *MockService_GetByID_Call {
	return &MockService_GetByID_Call{Call: _e.mock.On("GetByID",
		append([]any{id}, opts...)...)}
}

func (_c *MockService_GetByID_Call) Run(run func(id uint64, opts ...database.Option)) *MockService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 []database.Option
		var variadicArgs []database.Option
		if len(args) > 1 {
			variadicArgs = args[1].([]database.Option)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockService_GetByID_Call) Return(user *model.User, err error) *MockService_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_GetByID_Call) RunAndReturn(run func(id uint64, opts ...database.Option) (*model.User, error)) *MockService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function for the type MockService
func (_mock *MockService) GetByUsername(username string, opts ...database.Option) (*model.User, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(username, opts)
	} else {
		tmpRet = _mock.Called(username)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...database.Option) (*model.User, error)); ok {
		return returnFunc(username, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...database.Option) *model.User); ok {
		r0 = returnFunc(username, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...database.Option) error); ok {
		r1 = returnFunc(username, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type MockService_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - username string
//   - opts ...database.Option
func (_e *MockService_Expecter) GetByUsername(username any, opts ...any) *MockService_GetByUsername_Call {
	return &MockService_GetByUsername_Call{Call: _e.mock.On("GetByUsername",
		append([]any{username}, opts...)...)}
}

func (_c *MockService_GetByUsername_Call) Run(run func(username string, opts ...database.Option)) *MockService_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []database.Option
		var variadicArgs []database.Option
		if len(args) > 1 {
			variadicArgs = args[1].([]database.Option)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockService_GetByUsername_Call) Return(user *model.User, err error) *MockService_GetByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_GetByUsername_Call) RunAndReturn(run func(username string, opts ...database.Option) (*model.User, error)) *MockService_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// GetSelf provides a mock function for the type MockService
func (_mock *MockService) GetSelf(id uint64) (*model.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetSelf")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetSelf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSelf'
type MockService_GetSelf_Call struct {
	*mock.Call
}

// GetSelf is a helper method to define mock.On call
//   - id uint64
func (_e *MockService_Expecter) GetSelf(id any) *MockService_GetSelf_Call {
	return &MockService_GetSelf_Call{Call: _e.mock.On("GetSelf", id)}
}

func (_c *MockService_GetSelf_Call) Run(run func(id uint64)) *MockService_GetSelf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetSelf_Call) Return(user *model.User, err error) *MockService_GetSelf_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_GetSelf_Call) RunAndReturn(run func(id uint64) (*model.User, error)) *MockService_GetSelf_Call {
	_c.Call.Return(run)
	return _c
}

// SpendCharge provides a mock function for the type MockService
func (_mock *MockService) SpendCharge(id uint64, pixelsToSpend uint, opts ...database.Option) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(id, pixelsToSpend, opts)
	} else {
		tmpRet = _mock.Called(id, pixelsToSpend)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SpendCharge")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint, ...database.Option) error); ok {
		r0 = returnFunc(id, pixelsToSpend, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SpendCharge_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SpendCharge'
type MockService_SpendCharge_Call struct {
	*mock.Call
}

// SpendCharge is a helper method to define mock.On call
//   - id uint64
//   - pixelsToSpend uint
//   - opts ...database.Option
func (_e *MockService_Expecter) SpendCharge(id any, pixelsToSpend any, opts ...any) *MockService_SpendCharge_Call {
	return &MockService_SpendCharge_Call{Call: _e.mock.On("SpendCharge",
		append([]any{id, pixelsToSpend}, opts...)...)}
}

func (_c *MockService_SpendCharge_Call) Run(run func(id uint64, pixelsToSpend uint, opts ...database.Option)) *MockService_SpendCharge_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 []database.Option
		var variadicArgs []database.Option
		if len(args) > 2 {
			variadicArgs = args[2].([]database.Option)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockService_SpendCharge_Call) Return(err error) *MockService_SpendCharge_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SpendCharge_Call) RunAndReturn(run func(id uint64, pixelsToSpend uint, opts ...database.Option) error) *MockService_SpendCharge_Call {
	_c.Call.Return(run)
	return _c
}

// SyncAndGet provides a mock function for the type MockService
func (_mock *MockService) SyncAndGet(id uint64) (*model.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for SyncAndGet")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_SyncAndGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncAndGet'
type MockService_SyncAndGet_Call struct {
	*mock.Call
}

// SyncAndGet is a helper method to define mock.On call
//   - id uint64
func (_e *MockService_Expecter) SyncAndGet(id any) *MockService_SyncAndGet_Call {
	return &MockService_SyncAndGet_Call{Call: _e.mock.On("SyncAndGet", id)}
}

func (_c *MockService_SyncAndGet_Call) Run(run func(id uint64)) *MockService_SyncAndGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_SyncAndGet_Call) Return(user *model.User, err error) *MockService_SyncAndGet_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_SyncAndGet_Call) RunAndReturn(run func(id uint64) (*model.User, error)) *MockService_SyncAndGet_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(user *model.User, opts ...database.Option) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(user, opts)
	} else {
		tmpRet = _mock.Called(user)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.User, ...database.Option) error); ok {
		r0 = returnFunc(user, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - user *model.User
//   - opts ...database.Option
func (_e *MockService_Expecter) Update(user any, opts ...any) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update",
		append([]any{user}, opts...)...)}
}

func (_c *MockService_Update_Call) Run(run func(user *model.User, opts ...database.Option)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.User
		if args[0] != nil {
			arg0 = args[0].(*model.User)
		}
		var arg1 []database.Option
		var variadicArgs []database.Option
		if len(args) > 1 {
			variadicArgs = args[1].([]database.Option)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(err error) *MockService_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(user *model.User, opts ...database.Option) error) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}
