// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user

import (
	"go-place/internal/database"
	"go-place/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(user *model.User, opts ...database.Option) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(user, opts)
	} else {
		tmpRet = _mock.Called(user)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.User, ...database.Option) error); ok {
		r0 = returnFunc(user, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - user *model.User
//   - opts ...database.Option
func (_e *MockRepository_Expecter) Create(user any, opts ...any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create",
		append([]any{user}, opts...)...)}
}

func (_c *MockRepository_Create_Call) Run(run func(user *model.User, opts ...database.Option)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.User
		if args[0] != nil {
			arg0 = args[0].(*model.User)
		}
		var arg1 []database.Option
		var variadicArgs []database.Option
		if len(args) > 1 {
			variadicArgs = args[1].([]database.Option)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(user *model.User, opts ...database.Option) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockRepository_Expecter) Delete(id any) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(id uint64)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(err error) *MockRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(id uint64) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockRepository
func (_mock *MockRepository) GetAll(opts ...database.Option) ([]model.User, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(opts)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...database.Option) ([]model.User, error)); ok {
		return returnFunc(opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(...database.Option) []model.User); ok {
		r0 = returnFunc(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...database.Option) error); ok {
		r1 = returnFunc(opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - opts ...database.Option
func (_e *MockRepository_Expecter) GetAll(opts ...any) *MockRepository_GetAll_Call {
	return &MockRepository_GetAll_Call{Call: _e.mock.On("GetAll",
		append([]any{}, opts...)...)}
}

func (_c *MockRepository_GetAll_Call) Run(run func(opts ...database.Option)) *MockRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []database.Option
		var variadicArgs []database.Option
		if len(args) > 0 {
			variadicArgs = args[0].([]database.Option)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockRepository_GetAll_Call) Return(users []model.User, err error) *MockRepository_GetAll_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockRepository_GetAll_Call) RunAndReturn(run func(opts ...database.Option) ([]model.User, error)) *MockRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByID(id uint64, opts ...database.Option) (*model.User, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(id, opts)
	} else {
		tmpRet = _mock.Called(id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, ...database.Option) (*model.User, error)); ok {
		return returnFunc(id, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, ...database.Option) *model.User); ok {
		r0 = returnFunc(id, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, ...database.Option) error); ok {
		r1 = returnFunc(id, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint64
//   - opts ...database.Option
func (_e *MockRepository_Expecter) GetByID(id any, opts ...any) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID",
		append([]any{id}, opts...)...)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(id uint64, opts ...database.Option)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 []database.Option
		var variadicArgs []database.Option
		if len(args) > 1 {
			variadicArgs = args[1].([]database.Option)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(user *model.User, err error) *MockRepository_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(id uint64, opts ...database.Option) (*model.User, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByUsername(username string, opts ...database.Option) (*model.User, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(username, opts)
	} else {
		tmpRet = _mock.Called(username)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...database.Option) (*model.User, error)); ok {
		return returnFunc(username, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...database.Option) *model.User); ok {
		r0 = returnFunc(username, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...database.Option) error); ok {
		r1 = returnFunc(username, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type MockRepository_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - username string
//   - opts ...database.Option
func (_e *MockRepository_Expecter) GetByUsername(username any, opts ...any) *MockRepository_GetByUsername_Call {
	return &MockRepository_GetByUsername_Call{Call: _e.mock.On("GetByUsername",
		append([]any{username}, opts...)...)}
}

func (_c *MockRepository_GetByUsername_Call) Run(run func(username string, opts ...database.Option)) *MockRepository_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []database.Option
		var variadicArgs []database.Option
		if len(args) > 1 {
			variadicArgs = args[1].([]database.Option)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRepository_GetByUsername_Call) Return(user *model.User, err error) *MockRepository_GetByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_GetByUsername_Call) RunAndReturn(run func(username string, opts ...database.Option) (*model.User, error)) *MockRepository_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository) Update(user *model.User, opts ...database.Option) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(user, opts)
	} else {
		tmpRet = _mock.Called(user)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.User, ...database.Option) error); ok {
		r0 = returnFunc(user, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - user *model.User
//   - opts ...database.Option
func (_e *MockRepository_Expecter) Update(user any, opts ...any) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update",
		append([]any{user}, opts...)...)}
}

func (_c *MockRepository_Update_Call) Run(run func(user *model.User, opts ...database.Option)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.User
		if args[0] != nil {
			arg0 = args[0].(*model.User)
		}
		var arg1 []database.Option
		var variadicArgs []database.Option
		if len(args) > 1 {
			variadicArgs = args[1].([]database.Option)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(err error) *MockRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(user *model.User, opts ...database.Option) error) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
