// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package websocket

import (
	"go-place/internal/transport/websocket"
	"go-place/internal/transport/websocket/message"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHub creates a new instance of MockHub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHub {
	mock := &MockHub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHub is an autogenerated mock type for the Hub type
type MockHub struct {
	mock.Mock
}

type MockHub_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHub) EXPECT() *MockHub_Expecter {
	return &MockHub_Expecter{mock: &_m.Mock}
}

// Broadcast provides a mock function for the type MockHub
func (_mock *MockHub) Broadcast(message1 message.Base) {
	_mock.Called(message1)
	return
}

// MockHub_Broadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Broadcast'
type MockHub_Broadcast_Call struct {
	*mock.Call
}

// Broadcast is a helper method to define mock.On call
//   - message1 message.Base
func (_e *MockHub_Expecter) Broadcast(message1 any) *MockHub_Broadcast_Call {
	return &MockHub_Broadcast_Call{Call: _e.mock.On("Broadcast", message1)}
}

func (_c *MockHub_Broadcast_Call) Run(run func(message1 message.Base)) *MockHub_Broadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 message.Base
		if args[0] != nil {
			arg0 = args[0].(message.Base)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHub_Broadcast_Call) Return() *MockHub_Broadcast_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHub_Broadcast_Call) RunAndReturn(run func(message1 message.Base)) *MockHub_Broadcast_Call {
	_c.Run(run)
	return _c
}

// Register provides a mock function for the type MockHub
func (_mock *MockHub) Register(client websocket.Client) {
	_mock.Called(client)
	return
}

// MockHub_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockHub_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - client websocket.Client
func (_e *MockHub_Expecter) Register(client any) *MockHub_Register_Call {
	return &MockHub_Register_Call{Call: _e.mock.On("Register", client)}
}

func (_c *MockHub_Register_Call) Run(run func(client websocket.Client)) *MockHub_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 websocket.Client
		if args[0] != nil {
			arg0 = args[0].(websocket.Client)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHub_Register_Call) Return() *MockHub_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHub_Register_Call) RunAndReturn(run func(client websocket.Client)) *MockHub_Register_Call {
	_c.Run(run)
	return _c
}

// Run provides a mock function for the type MockHub
func (_mock *MockHub) Run() {
	_mock.Called()
	return
}

// MockHub_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockHub_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockHub_Expecter) Run() *MockHub_Run_Call {
	return &MockHub_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockHub_Run_Call) Run(run func()) *MockHub_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHub_Run_Call) Return() *MockHub_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHub_Run_Call) RunAndReturn(run func()) *MockHub_Run_Call {
	_c.Run(run)
	return _c
}

// Unregister provides a mock function for the type MockHub
func (_mock *MockHub) Unregister(client websocket.Client) {
	_mock.Called(client)
	return
}

// MockHub_Unregister_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unregister'
type MockHub_Unregister_Call struct {
	*mock.Call
}

// Unregister is a helper method to define mock.On call
//   - client websocket.Client
func (_e *MockHub_Expecter) Unregister(client any) *MockHub_Unregister_Call {
	return &MockHub_Unregister_Call{Call: _e.mock.On("Unregister", client)}
}

func (_c *MockHub_Unregister_Call) Run(run func(client websocket.Client)) *MockHub_Unregister_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 websocket.Client
		if args[0] != nil {
			arg0 = args[0].(websocket.Client)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHub_Unregister_Call) Return() *MockHub_Unregister_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHub_Unregister_Call) RunAndReturn(run func(client websocket.Client)) *MockHub_Unregister_Call {
	_c.Run(run)
	return _c
}
