// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package websocket

import (
	"github.com/gofiber/fiber/v3"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Upgrade provides a mock function for the type MockHandler
func (_mock *MockHandler) Upgrade() fiber.Handler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Upgrade")
	}

	var r0 fiber.Handler
	if returnFunc, ok := ret.Get(0).(func() fiber.Handler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fiber.Handler)
		}
	}
	return r0
}

// MockHandler_Upgrade_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upgrade'
type MockHandler_Upgrade_Call struct {
	*mock.Call
}

// Upgrade is a helper method to define mock.On call
func (_e *MockHandler_Expecter) Upgrade() *MockHandler_Upgrade_Call {
	return &MockHandler_Upgrade_Call{Call: _e.mock.On("Upgrade")}
}

func (_c *MockHandler_Upgrade_Call) Run(run func()) *MockHandler_Upgrade_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_Upgrade_Call) Return(v fiber.Handler) *MockHandler_Upgrade_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockHandler_Upgrade_Call) RunAndReturn(run func() fiber.Handler) *MockHandler_Upgrade_Call {
	_c.Call.Return(run)
	return _c
}
