// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package websocket

import (
	"go-place/internal/transport/websocket/message"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockClient
func (_mock *MockClient) Close() {
	_mock.Called()
	return
}

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	return &MockClient_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Close_Call) Return() *MockClient_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_Close_Call) RunAndReturn(run func()) *MockClient_Close_Call {
	_c.Run(run)
	return _c
}

// Send provides a mock function for the type MockClient
func (_mock *MockClient) Send(msg message.Base) {
	_mock.Called(msg)
	return
}

// MockClient_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockClient_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - msg message.Base
func (_e *MockClient_Expecter) Send(msg any) *MockClient_Send_Call {
	return &MockClient_Send_Call{Call: _e.mock.On("Send", msg)}
}

func (_c *MockClient_Send_Call) Run(run func(msg message.Base)) *MockClient_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 message.Base
		if args[0] != nil {
			arg0 = args[0].(message.Base)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_Send_Call) Return() *MockClient_Send_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_Send_Call) RunAndReturn(run func(msg message.Base)) *MockClient_Send_Call {
	_c.Run(run)
	return _c
}

// Write provides a mock function for the type MockClient
func (_mock *MockClient) Write() {
	_mock.Called()
	return
}

// MockClient_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockClient_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
func (_e *MockClient_Expecter) Write() *MockClient_Write_Call {
	return &MockClient_Write_Call{Call: _e.mock.On("Write")}
}

func (_c *MockClient_Write_Call) Run(run func()) *MockClient_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Write_Call) Return() *MockClient_Write_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockClient_Write_Call) RunAndReturn(run func()) *MockClient_Write_Call {
	_c.Run(run)
	return _c
}
