// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pixel

import (
	"go-place/internal/database"
	"go-place/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockRepository
func (_mock *MockRepository) Create(pixel *model.Pixel) error {
	ret := _mock.Called(pixel)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Pixel) error); ok {
		r0 = returnFunc(pixel)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - pixel *model.Pixel
func (_e *MockRepository_Expecter) Create(pixel any) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", pixel)}
}

func (_c *MockRepository_Create_Call) Run(run func(pixel *model.Pixel)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Pixel
		if args[0] != nil {
			arg0 = args[0].(*model.Pixel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(err error) *MockRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(pixel *model.Pixel) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockRepository_Expecter) Delete(id any) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockRepository_Delete_Call) Run(run func(id uint64)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(err error) *MockRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(id uint64) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockRepository
func (_mock *MockRepository) GetAll(opts ...database.Option) ([]model.Pixel, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(opts)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Pixel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...database.Option) ([]model.Pixel, error)); ok {
		return returnFunc(opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(...database.Option) []model.Pixel); ok {
		r0 = returnFunc(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Pixel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...database.Option) error); ok {
		r1 = returnFunc(opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - opts ...database.Option
func (_e *MockRepository_Expecter) GetAll(opts ...any) *MockRepository_GetAll_Call {
	return &MockRepository_GetAll_Call{Call: _e.mock.On("GetAll",
		append([]any{}, opts...)...)}
}

func (_c *MockRepository_GetAll_Call) Run(run func(opts ...database.Option)) *MockRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []database.Option
		var variadicArgs []database.Option
		if len(args) > 0 {
			variadicArgs = args[0].([]database.Option)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockRepository_GetAll_Call) Return(pixels []model.Pixel, err error) *MockRepository_GetAll_Call {
	_c.Call.Return(pixels, err)
	return _c
}

func (_c *MockRepository_GetAll_Call) RunAndReturn(run func(opts ...database.Option) ([]model.Pixel, error)) *MockRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCoordinates provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByCoordinates(x uint64, y uint64) (*model.Pixel, error) {
	ret := _mock.Called(x, y)

	if len(ret) == 0 {
		panic("no return value specified for GetByCoordinates")
	}

	var r0 *model.Pixel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) (*model.Pixel, error)); ok {
		return returnFunc(x, y)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *model.Pixel); ok {
		r0 = returnFunc(x, y)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Pixel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = returnFunc(x, y)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByCoordinates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCoordinates'
type MockRepository_GetByCoordinates_Call struct {
	*mock.Call
}

// GetByCoordinates is a helper method to define mock.On call
//   - x uint64
//   - y uint64
func (_e *MockRepository_Expecter) GetByCoordinates(x any, y any) *MockRepository_GetByCoordinates_Call {
	return &MockRepository_GetByCoordinates_Call{Call: _e.mock.On("GetByCoordinates", x, y)}
}

func (_c *MockRepository_GetByCoordinates_Call) Run(run func(x uint64, y uint64)) *MockRepository_GetByCoordinates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetByCoordinates_Call) Return(pixel *model.Pixel, err error) *MockRepository_GetByCoordinates_Call {
	_c.Call.Return(pixel, err)
	return _c
}

func (_c *MockRepository_GetByCoordinates_Call) RunAndReturn(run func(x uint64, y uint64) (*model.Pixel, error)) *MockRepository_GetByCoordinates_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetByID(id uint64) (*model.Pixel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Pixel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.Pixel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.Pixel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Pixel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint64
func (_e *MockRepository_Expecter) GetByID(id any) *MockRepository_GetByID_Call {
	return &MockRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockRepository_GetByID_Call) Run(run func(id uint64)) *MockRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetByID_Call) Return(pixel *model.Pixel, err error) *MockRepository_GetByID_Call {
	_c.Call.Return(pixel, err)
	return _c
}

func (_c *MockRepository_GetByID_Call) RunAndReturn(run func(id uint64) (*model.Pixel, error)) *MockRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockRepository
func (_mock *MockRepository) Update(pixel *model.Pixel) error {
	ret := _mock.Called(pixel)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Pixel) error); ok {
		r0 = returnFunc(pixel)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - pixel *model.Pixel
func (_e *MockRepository_Expecter) Update(pixel any) *MockRepository_Update_Call {
	return &MockRepository_Update_Call{Call: _e.mock.On("Update", pixel)}
}

func (_c *MockRepository_Update_Call) Run(run func(pixel *model.Pixel)) *MockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Pixel
		if args[0] != nil {
			arg0 = args[0].(*model.Pixel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Update_Call) Return(err error) *MockRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Update_Call) RunAndReturn(run func(pixel *model.Pixel) error) *MockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockRepository
func (_mock *MockRepository) Upsert(pixels []model.Pixel, opts ...database.Option) ([]model.Pixel, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(pixels, opts)
	} else {
		tmpRet = _mock.Called(pixels)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 []model.Pixel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]model.Pixel, ...database.Option) ([]model.Pixel, error)); ok {
		return returnFunc(pixels, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func([]model.Pixel, ...database.Option) []model.Pixel); ok {
		r0 = returnFunc(pixels, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Pixel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]model.Pixel, ...database.Option) error); ok {
		r1 = returnFunc(pixels, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - pixels []model.Pixel
//   - opts ...database.Option
func (_e *MockRepository_Expecter) Upsert(pixels any, opts ...any) *MockRepository_Upsert_Call {
	return &MockRepository_Upsert_Call{Call: _e.mock.On("Upsert",
		append([]any{pixels}, opts...)...)}
}

func (_c *MockRepository_Upsert_Call) Run(run func(pixels []model.Pixel, opts ...database.Option)) *MockRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []model.Pixel
		if args[0] != nil {
			arg0 = args[0].([]model.Pixel)
		}
		var arg1 []database.Option
		var variadicArgs []database.Option
		if len(args) > 1 {
			variadicArgs = args[1].([]database.Option)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRepository_Upsert_Call) Return(pixels1 []model.Pixel, err error) *MockRepository_Upsert_Call {
	_c.Call.Return(pixels1, err)
	return _c
}

func (_c *MockRepository_Upsert_Call) RunAndReturn(run func(pixels []model.Pixel, opts ...database.Option) ([]model.Pixel, error)) *MockRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
