// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pixel

import (
	"go-place/internal/database"
	"go-place/internal/model"
	"go-place/internal/model/request"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// BuildCanvas provides a mock function for the type MockService
func (_mock *MockService) BuildCanvas() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BuildCanvas")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_BuildCanvas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildCanvas'
type MockService_BuildCanvas_Call struct {
	*mock.Call
}

// BuildCanvas is a helper method to define mock.On call
func (_e *MockService_Expecter) BuildCanvas() *MockService_BuildCanvas_Call {
	return &MockService_BuildCanvas_Call{Call: _e.mock.On("BuildCanvas")}
}

func (_c *MockService_BuildCanvas_Call) Run(run func()) *MockService_BuildCanvas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_BuildCanvas_Call) Return(err error) *MockService_BuildCanvas_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_BuildCanvas_Call) RunAndReturn(run func() error) *MockService_BuildCanvas_Call {
	_c.Call.Return(run)
	return _c
}

// Change provides a mock function for the type MockService
func (_mock *MockService) Change(pixels []request.ChangePixel, newAuthor uint64) ([]model.Pixel, error) {
	ret := _mock.Called(pixels, newAuthor)

	if len(ret) == 0 {
		panic("no return value specified for Change")
	}

	var r0 []model.Pixel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]request.ChangePixel, uint64) ([]model.Pixel, error)); ok {
		return returnFunc(pixels, newAuthor)
	}
	if returnFunc, ok := ret.Get(0).(func([]request.ChangePixel, uint64) []model.Pixel); ok {
		r0 = returnFunc(pixels, newAuthor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Pixel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]request.ChangePixel, uint64) error); ok {
		r1 = returnFunc(pixels, newAuthor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type MockService_Change_Call struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//   - pixels []request.ChangePixel
//   - newAuthor uint64
func (_e *MockService_Expecter) Change(pixels any, newAuthor any) *MockService_Change_Call {
	return &MockService_Change_Call{Call: _e.mock.On("Change", pixels, newAuthor)}
}

func (_c *MockService_Change_Call) Run(run func(pixels []request.ChangePixel, newAuthor uint64)) *MockService_Change_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []request.ChangePixel
		if args[0] != nil {
			arg0 = args[0].([]request.ChangePixel)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Change_Call) Return(pixels1 []model.Pixel, err error) *MockService_Change_Call {
	_c.Call.Return(pixels1, err)
	return _c
}

func (_c *MockService_Change_Call) RunAndReturn(run func(pixels []request.ChangePixel, newAuthor uint64) ([]model.Pixel, error)) *MockService_Change_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockService
func (_mock *MockService) Create(pixel *model.Pixel) error {
	ret := _mock.Called(pixel)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Pixel) error); ok {
		r0 = returnFunc(pixel)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - pixel *model.Pixel
func (_e *MockService_Expecter) Create(pixel any) *MockService_Create_Call {
	return &MockService_Create_Call{Call: _e.mock.On("Create", pixel)}
}

func (_c *MockService_Create_Call) Run(run func(pixel *model.Pixel)) *MockService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Pixel
		if args[0] != nil {
			arg0 = args[0].(*model.Pixel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Create_Call) Return(err error) *MockService_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Create_Call) RunAndReturn(run func(pixel *model.Pixel) error) *MockService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(id uint64) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id uint64
func (_e *MockService_Expecter) Delete(id any) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockService_Delete_Call) Run(run func(id uint64)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(id uint64) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockService
func (_mock *MockService) GetAll(opts ...database.Option) ([]model.Pixel, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(opts)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []model.Pixel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...database.Option) ([]model.Pixel, error)); ok {
		return returnFunc(opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(...database.Option) []model.Pixel); ok {
		r0 = returnFunc(opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Pixel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(...database.Option) error); ok {
		r1 = returnFunc(opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockService_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - opts ...database.Option
func (_e *MockService_Expecter) GetAll(opts ...any) *MockService_GetAll_Call {
	return &MockService_GetAll_Call{Call: _e.mock.On("GetAll",
		append([]any{}, opts...)...)}
}

func (_c *MockService_GetAll_Call) Run(run func(opts ...database.Option)) *MockService_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []database.Option
		var variadicArgs []database.Option
		if len(args) > 0 {
			variadicArgs = args[0].([]database.Option)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockService_GetAll_Call) Return(pixels []model.Pixel, err error) *MockService_GetAll_Call {
	_c.Call.Return(pixels, err)
	return _c
}

func (_c *MockService_GetAll_Call) RunAndReturn(run func(opts ...database.Option) ([]model.Pixel, error)) *MockService_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetBinaryCanvas provides a mock function for the type MockService
func (_mock *MockService) GetBinaryCanvas() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBinaryCanvas")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetBinaryCanvas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBinaryCanvas'
type MockService_GetBinaryCanvas_Call struct {
	*mock.Call
}

// GetBinaryCanvas is a helper method to define mock.On call
func (_e *MockService_Expecter) GetBinaryCanvas() *MockService_GetBinaryCanvas_Call {
	return &MockService_GetBinaryCanvas_Call{Call: _e.mock.On("GetBinaryCanvas")}
}

func (_c *MockService_GetBinaryCanvas_Call) Run(run func()) *MockService_GetBinaryCanvas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetBinaryCanvas_Call) Return(bytes []byte, err error) *MockService_GetBinaryCanvas_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockService_GetBinaryCanvas_Call) RunAndReturn(run func() ([]byte, error)) *MockService_GetBinaryCanvas_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCoordinates provides a mock function for the type MockService
func (_mock *MockService) GetByCoordinates(x uint64, y uint64) (*model.Pixel, error) {
	ret := _mock.Called(x, y)

	if len(ret) == 0 {
		panic("no return value specified for GetByCoordinates")
	}

	var r0 *model.Pixel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) (*model.Pixel, error)); ok {
		return returnFunc(x, y)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *model.Pixel); ok {
		r0 = returnFunc(x, y)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Pixel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64) error); ok {
		r1 = returnFunc(x, y)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetByCoordinates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCoordinates'
type MockService_GetByCoordinates_Call struct {
	*mock.Call
}

// GetByCoordinates is a helper method to define mock.On call
//   - x uint64
//   - y uint64
func (_e *MockService_Expecter) GetByCoordinates(x any, y any) *MockService_GetByCoordinates_Call {
	return &MockService_GetByCoordinates_Call{Call: _e.mock.On("GetByCoordinates", x, y)}
}

func (_c *MockService_GetByCoordinates_Call) Run(run func(x uint64, y uint64)) *MockService_GetByCoordinates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetByCoordinates_Call) Return(pixel *model.Pixel, err error) *MockService_GetByCoordinates_Call {
	_c.Call.Return(pixel, err)
	return _c
}

func (_c *MockService_GetByCoordinates_Call) RunAndReturn(run func(x uint64, y uint64) (*model.Pixel, error)) *MockService_GetByCoordinates_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockService
func (_mock *MockService) GetByID(id uint64) (*model.Pixel, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.Pixel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*model.Pixel, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *model.Pixel); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Pixel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id uint64
func (_e *MockService_Expecter) GetByID(id any) *MockService_GetByID_Call {
	return &MockService_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *MockService_GetByID_Call) Run(run func(id uint64)) *MockService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetByID_Call) Return(pixel *model.Pixel, err error) *MockService_GetByID_Call {
	_c.Call.Return(pixel, err)
	return _c
}

func (_c *MockService_GetByID_Call) RunAndReturn(run func(id uint64) (*model.Pixel, error)) *MockService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockService
func (_mock *MockService) Update(pixel *model.Pixel) error {
	ret := _mock.Called(pixel)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Pixel) error); ok {
		r0 = returnFunc(pixel)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - pixel *model.Pixel
func (_e *MockService_Expecter) Update(pixel any) *MockService_Update_Call {
	return &MockService_Update_Call{Call: _e.mock.On("Update", pixel)}
}

func (_c *MockService_Update_Call) Run(run func(pixel *model.Pixel)) *MockService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Pixel
		if args[0] != nil {
			arg0 = args[0].(*model.Pixel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Update_Call) Return(err error) *MockService_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Update_Call) RunAndReturn(run func(pixel *model.Pixel) error) *MockService_Update_Call {
	_c.Call.Return(run)
	return _c
}
