// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pixel

import (
	"github.com/gofiber/fiber/v3"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Change provides a mock function for the type MockHandler
func (_mock *MockHandler) Change(ctx fiber.Ctx) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Change")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(fiber.Ctx) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_Change_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Change'
type MockHandler_Change_Call struct {
	*mock.Call
}

// Change is a helper method to define mock.On call
//   - ctx fiber.Ctx
func (_e *MockHandler_Expecter) Change(ctx any) *MockHandler_Change_Call {
	return &MockHandler_Change_Call{Call: _e.mock.On("Change", ctx)}
}

func (_c *MockHandler_Change_Call) Run(run func(ctx fiber.Ctx)) *MockHandler_Change_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(fiber.Ctx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_Change_Call) Return(err error) *MockHandler_Change_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_Change_Call) RunAndReturn(run func(ctx fiber.Ctx) error) *MockHandler_Change_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockHandler
func (_mock *MockHandler) GetAll(ctx fiber.Ctx) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(fiber.Ctx) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockHandler_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx fiber.Ctx
func (_e *MockHandler_Expecter) GetAll(ctx any) *MockHandler_GetAll_Call {
	return &MockHandler_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockHandler_GetAll_Call) Run(run func(ctx fiber.Ctx)) *MockHandler_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(fiber.Ctx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_GetAll_Call) Return(err error) *MockHandler_GetAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_GetAll_Call) RunAndReturn(run func(ctx fiber.Ctx) error) *MockHandler_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetBinaryCanvas provides a mock function for the type MockHandler
func (_mock *MockHandler) GetBinaryCanvas(ctx fiber.Ctx) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBinaryCanvas")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(fiber.Ctx) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_GetBinaryCanvas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBinaryCanvas'
type MockHandler_GetBinaryCanvas_Call struct {
	*mock.Call
}

// GetBinaryCanvas is a helper method to define mock.On call
//   - ctx fiber.Ctx
func (_e *MockHandler_Expecter) GetBinaryCanvas(ctx any) *MockHandler_GetBinaryCanvas_Call {
	return &MockHandler_GetBinaryCanvas_Call{Call: _e.mock.On("GetBinaryCanvas", ctx)}
}

func (_c *MockHandler_GetBinaryCanvas_Call) Run(run func(ctx fiber.Ctx)) *MockHandler_GetBinaryCanvas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(fiber.Ctx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_GetBinaryCanvas_Call) Return(err error) *MockHandler_GetBinaryCanvas_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_GetBinaryCanvas_Call) RunAndReturn(run func(ctx fiber.Ctx) error) *MockHandler_GetBinaryCanvas_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCoordinates provides a mock function for the type MockHandler
func (_mock *MockHandler) GetByCoordinates(ctx fiber.Ctx) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetByCoordinates")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(fiber.Ctx) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_GetByCoordinates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCoordinates'
type MockHandler_GetByCoordinates_Call struct {
	*mock.Call
}

// GetByCoordinates is a helper method to define mock.On call
//   - ctx fiber.Ctx
func (_e *MockHandler_Expecter) GetByCoordinates(ctx any) *MockHandler_GetByCoordinates_Call {
	return &MockHandler_GetByCoordinates_Call{Call: _e.mock.On("GetByCoordinates", ctx)}
}

func (_c *MockHandler_GetByCoordinates_Call) Run(run func(ctx fiber.Ctx)) *MockHandler_GetByCoordinates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(fiber.Ctx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_GetByCoordinates_Call) Return(err error) *MockHandler_GetByCoordinates_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_GetByCoordinates_Call) RunAndReturn(run func(ctx fiber.Ctx) error) *MockHandler_GetByCoordinates_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockHandler
func (_mock *MockHandler) GetByID(ctx fiber.Ctx) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(fiber.Ctx) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockHandler_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx fiber.Ctx
func (_e *MockHandler_Expecter) GetByID(ctx any) *MockHandler_GetByID_Call {
	return &MockHandler_GetByID_Call{Call: _e.mock.On("GetByID", ctx)}
}

func (_c *MockHandler_GetByID_Call) Run(run func(ctx fiber.Ctx)) *MockHandler_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 fiber.Ctx
		if args[0] != nil {
			arg0 = args[0].(fiber.Ctx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_GetByID_Call) Return(err error) *MockHandler_GetByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_GetByID_Call) RunAndReturn(run func(ctx fiber.Ctx) error) *MockHandler_GetByID_Call {
	_c.Call.Return(run)
	return _c
}
